# PyTorch fundamentals

In [2]:
# !pip install torch 

## Create Tensor
https://pytorch.org/docs/stable/torch.html#creation-ops

In [23]:
import torch
import numpy as np
from torch import nn

In [12]:
# Empty tensor
t_empty = torch.empty(2,2)
t_rand = torch.rand(2,2)
t_zeros = torch.zeros(2,2)
t_ones = torch.ones(2,2)

# Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.
t_eyes = torch.eye(3,3)

# Specify the data type for the tensor elements
t_full = torch.full((2,2), 34, dtype=torch.float)

t_multi_dim = torch.tensor([[1,3,2], [6,4,5], [5,8,7]])

# Print the tensors of your interest
print(t_multi_dim)
print(t_multi_dim.shape)

tensor([[1, 3, 2],
        [6, 4, 5],
        [5, 8, 7]])
torch.Size([3, 3])


# Common Tensor Functions

## torch.argmax() function

Index of maximum value

https://pytorch.org/docs/stable/generated/torch.argmax.html#torch.argmax

**torch.argmin()** does the opposite

https://pytorch.org/docs/stable/generated/torch.argmin.html#torch.argmin

In [13]:
# Create a tensor
tensor = torch.tensor([4, 1, 5, 3, 2])

# Find the index of the maximum value
max_index = torch.argmax(tensor)

print("Index of maximum value:", max_index)  # Output: tensor(2)
print("Value: ", tensor[max_index])

Index of maximum value: tensor(2)
Value:  tensor(5)


In [18]:
max_index = torch.argmax(t_multi_dim, dim=-1)
max_index

tensor([1, 0, 1])

## torch.topk() function

Returns the k largest elements of the given input tensor along a given dimension

https://pytorch.org/docs/stable/generated/torch.topk.html#torch.topk

In [20]:
# Create a tensor
tensor = torch.tensor([5, 1, 4, 2, 3])

# Get the 3 largest elements and their indices
top_k_values, top_k_indices = torch.topk(tensor, k=3)

print("Top 3 values:", top_k_values)   # Output: tensor([5, 4, 3])
print("Top 3 indices:", top_k_indices)  # Output: tensor([0, 2, 4])


Top 3 values: tensor([5, 4, 3])
Top 3 indices: tensor([0, 2, 4])


In [21]:
# Create a 2D tensor
tensor = torch.tensor([[4, 2, 6], [1, 3, 5], [7, 8, 9]])

# Get the top 2 values and indices along each row (dim=1)
top_k_values, top_k_indices = torch.topk(tensor, k=2, dim=1)

print("Top 2 values in each row:", top_k_values)   # Output: tensor([[6, 4], [5, 3], [9, 8]])
print("Top 2 indices in each row:", top_k_indices)  # Output: tensor([[2, 0], [2, 1], [0, 1]])


Top 2 values in each row: tensor([[6, 4],
        [5, 3],
        [9, 8]])
Top 2 indices in each row: tensor([[2, 0],
        [2, 1],
        [2, 1]])


# Common NN Activation Functions

## nn.softmax()

https://pytorch.org/docs/stable/generated/torch.nn.functional.softmax.html#torch.nn.functional.softmax

It is a mathematical function that transforms a tensor of real numbers into a probability distribution. It is often used to normalize the neural network’s output so that the sum of all outputs is equal to 1.

In [26]:
# Create a tensor of model output
logits = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax function
probabilities = nn.functional.softmax(logits, dim=-1)

print("Probabilities:", probabilities)  # Output: tensor([0.1192, 0.2712, 0.6096])
print("Sum of all probabilities:", torch.sum(probabilities)) # Output : 1.0

Probabilities: tensor([0.0900, 0.2447, 0.6652])
Sum of all probabilities: tensor(1.)


# Gradients

By default gradients are not calculated. In order to automatically calculate the gradients, set the requires_grad=True

https://pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor

In [66]:
tensor = torch.tensor([32.2])

print(tensor.requires_grad)

tensor = torch.tensor([32.2], requires_grad=True)

print(tensor.requires_grad)

False
True


In [15]:
import matplotlib.pyplot as plt

def y_func(x):
    return x*(x-3)*(x-7)

x = torch.tensor(np.arange(7.0,300.0, 2.0), requires_grad=True)

print(type(x))

y = y_func(x)

print(type(y))

gradient= torch.empty(x.shape[0]).fill_(1.0)

dy = torch.tensor(y,requires_grad=True).backward(gradient=gradient)

print(dy)
# plt.plot(x,y)
# plt.plot(x,dy)
plt.show()

NameError: name 'np' is not defined

# Tensor maths

https://pytorch.org/docs/stable/torch.html#math-operations

In [25]:
t_test = torch.tensor([[1,2,3], [3,4,5], [5,6,7]])

# Crteate a new tensor by subtracting 1 from each element
print('subtract 1 : ', t_test - 1)

print('multiple by 2 : ', t_test * 2)

subtract 1 :  tensor([[0, 1, 2],
        [2, 3, 4],
        [4, 5, 6]])
multiple by 2 :  tensor([[ 2,  4,  6],
        [ 6,  8, 10],
        [10, 12, 14]])


In [34]:
# Dot product operator
# i.e., matrix multiplacation

t_1 = torch.tensor([[1,2],[3,4],[5,6]])
t_2 = torch.tensor([[1,2],[3,4]])

print(t_1)
print(t_2)

t_1 @ t_2

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2],
        [3, 4]])


tensor([[ 7, 10],
        [15, 22],
        [23, 34]])

In [27]:
# Index of the element for which val = max value in tensor
torch.tensor([1,2,9,4,5,6,7]).argmax()

tensor(2)

# Create NN

- forward method does the computation
- 

In [48]:
import torch
import torch.nn as nn

In [51]:
# https://pytorch.org/docs/stable/generated/torch.nn.Linear.html

# Input feature tensor size = 2, Output feature tensor size = 3
layer_1 = nn.Linear(2,3)
activation_1 = nn.ReLU()

layer_2 = nn.Linear(3,2)
activation_2 = nn.ReLU()

model = nn.Sequential(
    layer_1,
    activation_1,
    layer_2,
    activation_2
)

In [53]:
print(f"Model structure: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure: Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=2, bias=True)
  (3): ReLU()
)


Layer: 0.weight | Size: torch.Size([3, 2]) | Values : tensor([[ 0.3293,  0.6854],
        [-0.3402, -0.3223]], grad_fn=<SliceBackward0>) 

Layer: 0.bias | Size: torch.Size([3]) | Values : tensor([-0.5806, -0.6471], grad_fn=<SliceBackward0>) 

Layer: 2.weight | Size: torch.Size([2, 3]) | Values : tensor([[-0.2085,  0.5761,  0.4243],
        [-0.1109, -0.3793,  0.3125]], grad_fn=<SliceBackward0>) 

Layer: 2.bias | Size: torch.Size([2]) | Values : tensor([-0.4078, -0.3010], grad_fn=<SliceBackward0>) 



In [62]:
x = torch.tensor([[1.0,2.0], [1.0,2.0], [1.0,2.0]])

x = torch.rand(3,2)

output = model(x)

output

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], grad_fn=<ReluBackward0>)